kind: Deployment   
apiVersion: apps/v1  
metadata:
  name: java  
spec:
  replicas: 2    
  selector:  
    matchLabels:
      app: java  
  template:
    metadata:
      name: unitedwebapp
      labels:
        app: java  
    spec: 
      nodeSelector:
        node: dbnode  
      containers:  
      - name: unitedwebapp
        image: unitedcore/united-web-app
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 256m
            memory: 128Mi
          limits:
            cpu: 3000m
            memory: 856Mi
---
kind: Service
apiVersion: v1
metadata:
  name: webappsvc
spec:
  type: NodePort
  ports:
  - targetPort: 8080
    port: 80
    nodePort: 31111
  selector:
    app: java